version: '3'
services:
  php:
    build: .
    container_name: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./public:/var/www/html
    links:
      - mysql
    ports:
      - 8000:80
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 8181:80
